apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-node-1780005157950-says
  description: E2E test Node.js application created at 2026-05-28T21:52:52.839Z
  annotations:
    github.com/project-slug: darede-labs/idp-test-node-1780005157950-says
    backstage.io/kubernetes-namespace: test-node-1780005157950-says
    backstage.io/kubernetes-label-selector: app=test-node-1780005157950-says
spec:
  type: service
  lifecycle: experimental
  owner: 
