apiVersion: v1
kind: Service
metadata:
  name: test-node-1780005157950-says
  namespace: test-node-1780005157950-says
  labels:
    app: test-node-1780005157950-says
    app.kubernetes.io/name: test-node-1780005157950-says
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app: test-node-1780005157950-says
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
